openapi: 3.0.0
info: 
  version: 1.0.0
  title: Cart
  description: Cart API V1
servers: 
  - url: https://hexapi.example.com
    description: API Server Description
paths: 
  /cart: 
   post: 
    operationId: getCartDetails
    tags: 
     - cart
    summary: Cart Details
    description: Cart Details
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/CartDetailsRequest'
    responses: 
     '200': 
      description: Get Cart Details
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/GetCartDetailsResponse'
     '404': 
      description: Method not found
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/ErrorResponse'
     '500': 
      description: Internal Server Error
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/ErrorResponse'
   delete: 
    operationId: removeFromCart
    tags: 
     - cart
    summary: Remove From Cart
    description: Remove From Cart
    responses: 
     '200': 
      description: Item Removed
      content: 
       application/json: 
        schema: 
         type: string
     '404': 
      description: Method not found
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/ErrorResponse'
     '500': 
      description: Internal Server Error
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/ErrorResponse'
  /cart/add: 
   post: 
    operationId: addToCart
    tags: 
     - cart
    summary: Add To Cart
    description: Add To Cart
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/AddToCartRequest'
    responses: 
     '200': 
      description: Add to cart successful
      content: 
       application/json: 
        schema: 
         type: string
     '404': 
      description: Method not found
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/ErrorResponse'
     '500': 
      description: Internal Server Error
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/ErrorResponse'
  /cart/empty: 
   delete: 
    operationId: emptyCart
    tags: 
     - cart
    summary: Empty Cart
    description: Empty Cart
    responses: 
     '200': 
      description: Cart Emptied
      content: 
       application/json: 
        schema: 
         type: string
     '404': 
      description: Method not found
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/ErrorResponse'
     '500': 
      description: Internal Server Error
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/ErrorResponse'
components: 
  schemas: 
   CartDetailsRequest: 
    type: object
    properties: 
     userid: 
      type: string
     storeid: 
      type: string
   AddToCartRequest: 
    type: object
    properties: 
     userid: 
      type: string
     storeid: 
      type: string
     menuitemid: 
      type: string
   EmptyCartRequest: 
    type: object
    properties: 
     userid: 
      type: string
     storeid: 
      type: string
   ErrorResponse: 
    type: object
    properties: 
     code: 
      type: integer
     message: 
      type: string
   RemoveFromCartRequest: 
    type: object
    properties: 
     userid: 
      type: string
     storeid: 
      type: string
     itemid: 
      type: string
   GetCartDetailsResponse: 
    type: object
    properties: 
     id: 
      type: string
     userid: 
      type: string
     storeid: 
      type: string
     menuitemids: 
      type: array
      items: 
       type: string
   Cart: 
    type: object
    properties: 
     id: 
      type: string
     userid: 
      type: string
     storeid: 
      type: string
     menuitemids: 
      type: array
      items: 
       type: string
