openapi: 3.0.0
info: 
  version: 1.0.0
  title: EIC-Admin-Exp-Api
  description: API description
servers: 
  - url: api
    description: API Server Description
paths: 
  /member: 
   post: 
    operationId: postmember
    tags: 
     - member
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/memberInsertRequest'
    parameters: 
     - $ref: '#/components/parameters/TenantIdentifierParam'
     - $ref: '#/components/parameters/client_secretParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/channelidParam'
    responses: 
     '200': 
      description: Success
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/memberpostResponse'
     '500': 
      description: Success
      content: 
       application/json: 
                                                    schema:
                                                     type: string
components: 
  schemas: 
   FaultException: 
    type: object
    properties: 
     Errors: 
      type: string
     Messages: 
      type: string
     Exceptions: 
      type: string
     Warnings: 
      type: string
     Success: 
      type: string
   memberpostResponse: 
    type: object
    properties: 
     FaultException: 
      type: object
      $ref: '#/components/schemas/FaultException'
     ResponseDetails: 
      type: object
      $ref: '#/components/schemas/ResponseDetails'
   ResponseDetails: 
    type: object
    properties: 
     PaymentException: 
      type: string
     SsaDeductRequested: 
      type: string
     ProcessPaymentReponse: 
      type: string
     IsBrokerCompliant: 
      type: string
   Member: 
    type: object
    properties: 
     MZipCode: 
      type: string
     Email: 
      type: string
     GreenEobReasonCode: 
      type: string
     MCity: 
      type: string
     BWritingCode: 
      type: string
     BrokerID: 
      type: string
     CellPhone: 
      type: string
     CurrentBalance: 
      type: string
     AltMemberId: 
      type: string
     Prefix: 
      type: string
     Gender: 
      type: string
     PlanName: 
      type: string
     PbpId: 
      type: string
     HICN: 
      type: string
     MemberId: 
      type: string
     MailNABPs: 
      type: string
     EnrollmentDate: 
      type: string
     MiddleInitial: 
      type: string
     MBI: 
      type: string
     DOB: 
      type: string
     Phone: 
      type: string
     BrokerAttestation: 
      type: string
     PbpCode: 
      type: string
     DisenrollmentDate: 
      type: string
     MAddress2: 
      type: string
     Status: 
      type: string
     MAddress1: 
      type: string
     PrimaryPharmacy: 
      type: string
     FirstName: 
      type: string
     ZipCode: 
      type: string
     PlanId: 
      type: string
     Address2: 
      type: string
     MState: 
      type: string
     Address1: 
      type: string
     City: 
      type: string
     GroupId: 
      type: string
     Pharmacies: 
      type: string
     MedicareNumber: 
      type: string
     MonthlyPremium: 
      type: string
     AltPhone: 
      type: string
     CMSConfirmationID: 
      type: string
     Year: 
      type: string
     State: 
      type: string
     LastName: 
      type: string
     EGWPDirectBill: 
      type: string
     IsBroker: 
      type: string
   memberInsertRequest: 
    type: object
    properties: 
     ReferralCode: 
      type: object
      $ref: '#/components/schemas/ReferralCode'
     Email: 
      type: object
      $ref: '#/components/schemas/Email'
     Address: 
      type: object
      $ref: '#/components/schemas/Address'
     Gender: 
      type: object
     Institution: 
      type: object
      $ref: '#/components/schemas/Institution'
     MiddleInitial: 
      type: object
      $ref: '#/components/schemas/MiddleInitial'
     BrokerAttestation: 
      type: object
     DateOfBirth: 
      type: object
      $ref: '#/components/schemas/DateOfBirth'
     PartAEffDate: 
      type: object
      $ref: '#/components/schemas/PartAEffDate'
     CmsConfirmationId: 
      type: object
      $ref: '#/components/schemas/CmsConfirmationId'
     AltPhone: 
      type: object
     spouseWorkInd: 
      type: object
      $ref: '#/components/schemas/spouseWorkInd'
     LastName: 
      type: object
      $ref: '#/components/schemas/LastName'
     ApplicationId: 
      type: object
      $ref: '#/components/schemas/ApplicationId'
     EmergencyContact: 
      type: object
      $ref: '#/components/schemas/EmergencyContact'
     HasEmergencyContact: 
      type: object
      $ref: '#/components/schemas/HasEmergencyContact'
     CellPhone: 
      type: object
     HasOtherCoverage: 
      type: object
     SepReason: 
      type: object
      $ref: '#/components/schemas/SepReason'
     Prefix: 
      type: object
      $ref: '#/components/schemas/Prefix'
     ApplicationDate: 
      type: object
      $ref: '#/components/schemas/ApplicationDate'
     selfWorkInd: 
      type: object
      $ref: '#/components/schemas/selfWorkInd'
     EnrollmentDate: 
      type: object
     OtherCoverage: 
      type: object
     Language: 
      type: object
     Phone: 
      type: object
      $ref: '#/components/schemas/Phone'
     altFormatRqst: 
      type: object
      $ref: '#/components/schemas/altFormatRqst'
     EnrollmentType: 
      type: object
      $ref: '#/components/schemas/EnrollmentType'
     PaymentType: 
      type: object
      $ref: '#/components/schemas/PaymentType'
     IsLongTermCare: 
      type: object
      $ref: '#/components/schemas/IsLongTermCare'
     DeductSsa: 
      type: object
     Broker: 
      type: object
      $ref: '#/components/schemas/Broker'
     LoginId: 
      type: object
      $ref: '#/components/schemas/LoginId'
     ZipCode: 
      type: object
      $ref: '#/components/schemas/ZipCode'
     StateCode: 
      type: object
      $ref: '#/components/schemas/StateCode'
     MailingAddress: 
      type: object
      $ref: '#/components/schemas/MailingAddress'
     HasBroker: 
      type: object
      $ref: '#/components/schemas/HasBroker'
     Plan: 
      type: object
     PartBEffDate: 
      type: object
      $ref: '#/components/schemas/PartBEffDate'
     SeparationReasonDescription: 
      type: object
      $ref: '#/components/schemas/SeparationReasonDescription'
     GroupId: 
      type: object
      $ref: '#/components/schemas/GroupId'
     Firstname: 
      type: object
      $ref: '#/components/schemas/Firstname'
     MedicareNumber: 
      type: object
     UserId: 
      type: object
      $ref: '#/components/schemas/UserId'
     ElectionType: 
      type: object
     IsRepresentative: 
      type: object
     BrokerAttestationType: 
      type: object
      $ref: '#/components/schemas/BrokerAttestationType'
     Representative: 
      type: object
     IsBroker: 
      type: object
   ReferralCode: 
    type: object
    properties: 
     required: 
      type: string
   Email: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
   properties: 
    type: object
    properties: 
     ZipCode: 
      type: string
     Address2: 
      type: string
     StateCode: 
      type: string
     Address1: 
      type: string
     City: 
      type: string
     Group: 
      type: string
     Id: 
      type: string
     Name: 
      type: string
     DateOfBirth: 
      type: string
     Status: 
      type: object
      $ref: '#/components/schemas/Status'
     Email: 
      type: string
     LicenseExpirationDate: 
      type: object
      $ref: '#/components/schemas/LicenseExpirationDate'
     Address: 
      type: object
      $ref: '#/components/schemas/Address'
     FirstName: 
      type: string
     AgentSuspended: 
      type: string
     NPN: 
      type: string
     SSN: 
      type: string
     LicenseState: 
      type: string
     Referral: 
      type: object
      $ref: '#/components/schemas/Referral'
     Phone: 
      type: string
     LicenseStatus: 
      type: string
     Relationship: 
      type: string
     LastName: 
      type: string
     WritingCode: 
      type: string
     MailAddress1: 
      type: string
     Deductible: 
      type: object
      $ref: '#/components/schemas/Deductible'
     IsEGWP: 
      type: object
     PlanYearStages: 
      type: object
      $ref: '#/components/schemas/PlanYearStages'
     PlanId: 
      type: object
      $ref: '#/components/schemas/PlanId'
     StateName: 
      type: string
     DeductibleDescription: 
      type: string
     Deminimis: 
      type: object
      $ref: '#/components/schemas/Deminimis'
     Premium: 
      type: object
      $ref: '#/components/schemas/Premium'
     PlanName: 
      type: string
     PlanDetails: 
      type: object
      $ref: '#/components/schemas/PlanDetails'
     GroupId: 
      type: string
     PbpDescription: 
      type: string
     Lis50: 
      type: object
      $ref: '#/components/schemas/Lis50'
     Lis75: 
      type: object
      $ref: '#/components/schemas/Lis75'
     State: 
      type: string
     Lis100: 
      type: object
      $ref: '#/components/schemas/Lis100'
     Lis25: 
      type: object
      $ref: '#/components/schemas/Lis25'
     PlanYear: 
      type: object
      $ref: '#/components/schemas/PlanYear'
     SkipDeductable: 
      type: object
      $ref: '#/components/schemas/SkipDeductable'
     Pbp: 
      type: string
   ZipCode: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
   Address2: 
    type: object
    properties: 
     required: 
      type: string
   StateCode: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
   Address1: 
    type: object
    properties: 
     required: 
      type: string
   City: 
    type: object
    properties: 
     required: 
      type: string
   Address: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
   Institution: 
    type: object
    properties: 
     required: 
      type: string
   MiddleInitial: 
    type: object
    properties: 
     required: 
      type: string
   DateOfBirth: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
   PartAEffDate: 
    type: object
    properties: 
     required: 
      type: string
   CmsConfirmationId: 
    type: object
    properties: 
     required: 
      type: string
   spouseWorkInd: 
    type: object
    properties: 
     required: 
      type: string
   LastName: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
   ApplicationId: 
    type: object
    properties: 
     required: 
      type: string
   EmergencyContact: 
    type: object
    properties: 
     required: 
      type: string
   HasEmergencyContact: 
    type: object
    properties: 
     required: 
      type: string
   SepReason: 
    type: object
    properties: 
     required: 
      type: string
   Prefix: 
    type: object
    properties: 
     required: 
      type: string
   ApplicationDate: 
    type: object
    properties: 
     required: 
      type: string
   selfWorkInd: 
    type: object
    properties: 
     required: 
      type: string
   Id: 
    type: object
    properties: 
     required: 
      type: string
   Name: 
    type: object
    properties: 
     required: 
      type: string
   Phone: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
   altFormatRqst: 
    type: object
    properties: 
     required: 
      type: string
   EnrollmentType: 
    type: object
    properties: 
     format: 
      type: string
   PaymentType: 
    type: object
    properties: 
     format: 
      type: string
   IsLongTermCare: 
    type: object
    properties: 
     required: 
      type: string
   Status: 
    type: object
    properties: 
     required: 
      type: string
     enum: 
      type: string
   LicenseExpirationDate: 
    type: object
    properties: 
     required: 
      type: string
   FirstName: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
   AgentSuspended: 
    type: object
    properties: 
     required: 
      type: string
   NPN: 
    type: object
    properties: 
     required: 
      type: string
   SSN: 
    type: object
    properties: 
     required: 
      type: string
   LicenseState: 
    type: object
    properties: 
     required: 
      type: string
   Referral: 
    type: object
    properties: 
     required: 
      type: string
   LicenseStatus: 
    type: object
    properties: 
     required: 
      type: string
   Relationship: 
    type: object
    properties: 
     required: 
      type: string
   WritingCode: 
    type: object
    properties: 
     required: 
      type: string
   MailAddress1: 
    type: object
    properties: 
     required: 
      type: string
   Broker: 
    type: object
    properties: 
     required: 
      type: string
   LoginId: 
    type: object
    properties: 
     required: 
      type: string
   MailingAddress: 
    type: object
    properties: 
     required: 
      type: string
   HasBroker: 
    type: object
    properties: 
     required: 
      type: string
   Deductible: 
    type: object
    properties: 
     required: 
      type: string
   items: 
    type: object
    properties: 
     type: 
      type: string
     type: 
      type: string
   PlanYearStages: 
    type: object
    properties: 
     required: 
      type: string
   PlanId: 
    type: object
    properties: 
     format: 
      type: string
   StateName: 
    type: object
    properties: 
     required: 
      type: string
   DeductibleDescription: 
    type: object
    properties: 
     required: 
      type: string
   Deminimis: 
    type: object
    properties: 
     required: 
      type: string
   Premium: 
    type: object
    properties: 
     required: 
      type: string
   PlanDetails: 
    type: object
    properties: 
     required: 
      type: string
   GroupId: 
    type: object
    properties: 
     required: 
      type: string
   PbpDescription: 
    type: object
    properties: 
     required: 
      type: string
   Lis50: 
    type: object
    properties: 
     required: 
      type: string
   Lis75: 
    type: object
    properties: 
     required: 
      type: string
   State: 
    type: object
    properties: 
     required: 
      type: string
   Lis100: 
    type: object
    properties: 
     required: 
      type: string
   Lis25: 
    type: object
    properties: 
     required: 
      type: string
   PlanYear: 
    type: object
    properties: 
     format: 
      type: string
   SkipDeductable: 
    type: object
    properties: 
     required: 
      type: string
   PartBEffDate: 
    type: object
    properties: 
     required: 
      type: string
   SeparationReasonDescription: 
    type: object
    properties: 
     required: 
      type: string
   Firstname: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
   UserId: 
    type: object
    properties: 
     required: 
      type: string
   BrokerAttestationType: 
    type: object
    properties: 
     required: 
      type: string
  parameters: 
   TenantIdentifierParam: 
    in: header
    name: TenantIdentifier
    required: false
    schema: 
     type: string
    description: Tenant Identifier
   client_secretParam: 
    in: header
    name: client_secret
    required: true
    schema: 
     type: string
    description: description of parameter passed
   client_idParam: 
    in: header
    name: client_id
    required: true
    schema: 
     type: string
    description: description of parameter passed
   channelidParam: 
    in: header
    name: channelid
    required: false
    schema: 
     type: string
     format: integer | nil
    description: Unique Id to determine the Client
