openapi: 3.0.0
info: 
  version: 1.0.0
  title: EIC-Admin-Exp-Api
  description: API description
servers: 
  - url: api
    description: API Server Description
paths: 
  /member: 
   post: 
    operationId: postmember
    tags: 
     - member
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/memberInsertRequest'
    parameters: 
     - $ref: '#/components/parameters/TenantIdentifierParam'
     - $ref: '#/components/parameters/client_secretParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/channelidParam'
    responses: 
     '200': 
      description: Success
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/memberpostResponse'
     '500': 
      description: Success
      content: 
       application/json: 
                                                    schema:
                                                     type: string
components: 
  schemas: 
   FaultException: 
    type: object
    properties: 
     Errors: 
      type: string
     Messages: 
      type: string
     Exceptions: 
      type: string
     Warnings: 
      type: string
     Success: 
      type: string
   memberpostResponse: 
    type: object
    properties: 
     FaultException: 
      type: object
      $ref: '#/components/schemas/FaultException'
     ResponseDetails: 
      type: object
      $ref: '#/components/schemas/ResponseDetails'
   ResponseDetails: 
    type: object
    properties: 
     PaymentException: 
      type: string
     SsaDeductRequested: 
      type: string
     ProcessPaymentReponse: 
      type: string
     IsBrokerCompliant: 
      type: string
   Member: 
    type: object
    properties: 
     MZipCode: 
      type: string
     Email: 
      type: string
     GreenEobReasonCode: 
      type: string
     MCity: 
      type: string
     BWritingCode: 
      type: string
     BrokerID: 
      type: string
     CellPhone: 
      type: string
     CurrentBalance: 
      type: string
     AltMemberId: 
      type: string
     Prefix: 
      type: string
     Gender: 
      type: string
     PlanName: 
      type: string
     PbpId: 
      type: string
     HICN: 
      type: string
     MemberId: 
      type: string
     MailNABPs: 
      type: string
     EnrollmentDate: 
      type: string
     MiddleInitial: 
      type: string
     MBI: 
      type: string
     DOB: 
      type: string
     Phone: 
      type: string
     BrokerAttestation: 
      type: string
     PbpCode: 
      type: string
     DisenrollmentDate: 
      type: string
     MAddress2: 
      type: string
     Status: 
      type: string
     MAddress1: 
      type: string
     PrimaryPharmacy: 
      type: string
     FirstName: 
      type: string
     ZipCode: 
      type: string
     PlanId: 
      type: string
     Address2: 
      type: string
     MState: 
      type: string
     Address1: 
      type: string
     City: 
      type: string
     GroupId: 
      type: string
     Pharmacies: 
      type: string
     MedicareNumber: 
      type: string
     MonthlyPremium: 
      type: string
     AltPhone: 
      type: string
     CMSConfirmationID: 
      type: string
     Year: 
      type: string
     State: 
      type: string
     LastName: 
      type: string
     EGWPDirectBill: 
      type: string
     IsBroker: 
      type: string
   memberInsertRequest: 
    type: object
    properties: 
     ReferralCode: 
      type: string
     Email: 
      type: string
     Gender: 
      type: string
     MiddleInitial: 
      type: string
     DateOfBirth: 
      type: string
     CmsConfirmationId: 
      type: string
     AltPhone: 
      type: string
     LastName: 
      type: string
     ApplicationId: 
      type: string
     CellPhone: 
      type: string
     SepReason: 
      type: string
     Prefix: 
      type: string
     ApplicationDate: 
      type: string
     Language: 
      type: string
     Phone: 
      type: string
     altFormatRqst: 
      type: string
     ZipCode: 
      type: string
     StateCode: 
      type: string
     SeparationReasonDescription: 
      type: string
     GroupId: 
      type: string
     Firstname: 
      type: string
     MedicareNumber: 
      type: string
     ElectionType: 
      type: string
     BrokerAttestationType: 
      type: string
  parameters: 
   TenantIdentifierParam: 
    in: header
    name: TenantIdentifier
    required: false
    schema: 
     type: string
    description: Tenant Identifier
   client_secretParam: 
    in: header
    name: client_secret
    required: true
    schema: 
     type: string
    description: description of parameter passed
   client_idParam: 
    in: header
    name: client_id
    required: true
    schema: 
     type: string
    description: description of parameter passed
   channelidParam: 
    in: header
    name: channelid
    required: false
    schema: 
     type: string
     format: integer | nil
    description: Unique Id to determine the Client
