openapi: 3.0.0
info: 
  version: 1.0.0
  title: EIC-Member-Data-Service-sapi
  description: API description
servers: 
  - url: api
    description: API Server Description
paths: 
  /auditLogByNameId: 
   get: 
    operationId: getauditLogByNameId
    tags: 
     - auditLogByNameId
    description: Description of path
    responses: 
     '200': 
      description: Success
      content: 
       application/json: 
                                                    schema:
                                                     type: string
     '500': 
      description: Success
      content: 
       application/json: 
