openapi: 3.0.0
info: 
  version: 1.0.0
  title: EIC-Admin-Exp-Api
  description: API description
servers: 
  - url: api
    description: API Server Description
paths: 
  /SSADeductExport/{UserName}: 
   get: 
    operationId: getSSADeductExport_UserName
    tags: 
     - SSADeductExport
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/UserNameParam'
     - $ref: '#/components/parameters/TenantIdentifierParam'
     - $ref: '#/components/parameters/client_secretParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/channelidParam'
    responses: 
     '200': 
      description: Success
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/SSADeductExportgetResponse'
     '500': 
      description: Success
      content: 
       application/json: 
                                                    schema:
                                                     type: string
  /sep: 
   get: 
    operationId: getsep
    tags: 
     - sep
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/client_secretParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/channelidParam'
    responses: 
     '200': 
      description: Success
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/sepgetResponse'
     '500': 
      description: Success
      content: 
       application/json: 
                                                    schema:
                                                     type: string
components: 
  schemas: 
   SSADeductExportgetResponse: 
    type: object
    properties: 
     SSADeductRequests: 
      type: string
   type: 
    type: object
    properties: 
     type: 
      type: string
     properties: 
      type: object
   SEPReasonID: 
    type: object
    properties: 
     format: 
      type: string
     type: 
      type: string
   MoreInfo: 
    type: object
    properties: 
     type: 
      type: string
   Code: 
    type: object
    properties: 
     type: 
      type: string
   ActiveFlag: 
    type: object
    properties: 
     type: 
      type: string
   Reason: 
    type: object
    properties: 
     type: 
      type: string
   sepgetResponse: 
    type: object
    properties: 
     type: 
      type: object
      $ref: '#/components/schemas/type'
  parameters: 
   UserNameParam: 
    in: path
    name: UserName
    required: true
    schema: 
     type: string
    description: Unique UserName
   TenantIdentifierParam: 
    in: header
    name: TenantIdentifier
    required: false
    schema: 
     type: string
    description: Tenant Identifier
   client_secretParam: 
    in: header
    name: client_secret
    required: true
    schema: 
     type: string
    description: description of parameter passed
   client_idParam: 
    in: header
    name: client_id
    required: true
    schema: 
     type: string
    description: description of parameter passed
   channelidParam: 
    in: header
    name: channelid
    required: false
    schema: 
     type: string
     format: integer | nil
    description: Unique Id to determine the Client
