openapi: 3.0.0
info: 
  version: 1.0.0
  title: EIC-Web-Exp-Api
  description: API description
servers: 
  - url: api
    description: API Server Description
paths: 
  /faqs: 
   get: 
    operationId: getfaqs
    tags: 
     - faqs
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/TenantIdentifierParam'
     - $ref: '#/components/parameters/client_secretParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/channelidParam'
    responses: 
     '200': 
      description: Success
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/faqsgetResponse'
     '500': 
      description: Success
      content: 
       application/json: 
                                                    schema:
                                                     type: string
  /pharmacy/search: 
   get: 
    operationId: getpharmacy_search
    tags: 
     - pharmacy
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/client_secretParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/channelidParam'
    responses: 
     '200': 
      description: Success
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/pharmacygetResponse'
     '500': 
      description: Internal Server Error
     '404': 
      description: Not found
  /MetaData: 
   get: 
    operationId: getMetaData
    tags: 
     - MetaData
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/client_secretParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/channelidParam'
    responses: 
     '200': 
      description: Success
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/MetaDatagetResponse'
     '500': 
      description: Internal Server Error
     '404': 
      description: Not found
  /disenrollmentReasons: 
   get: 
    operationId: getdisenrollmentReasons
    tags: 
     - disenrollmentReasons
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/client_secretParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/channelidParam'
    responses: 
     '200': 
      description: Success
      content: 
       application/json: 
                                                    schema:
                                                     type: string
     '500': 
      description: Success
      content: 
       application/json: 
                                                    schema:
                                                     type: string
  /webdocuments: 
   get: 
    operationId: getwebdocuments
    tags: 
     - webdocuments
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/client_secretParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/channelidParam'
    responses: 
     '200': 
      description: Success
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/webdocumentsgetResponse'
     '500': 
      description: Success
      content: 
       application/json: 
                                                    schema:
                                                     type: string
  /plan/search: 
   get: 
    operationId: getplan_search
    tags: 
     - plan
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/client_secretParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/channelidParam'
    responses: 
     '200': 
      description: Success
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/plangetResponse'
     '500': 
      description: Success
      content: 
       application/json: 
                                                    schema:
                                                     type: string
  /glossary: 
   get: 
    operationId: getglossary
    tags: 
     - glossary
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/client_secretParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/channelidParam'
    responses: 
     '200': 
      description: Success
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/glossarygetResponse'
     '500': 
      description: Success
      content: 
       application/json: 
                                                    schema:
                                                     type: string
  /eventlog: 
   post: 
    operationId: posteventlog
    tags: 
     - eventlog
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/client_secretParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/channelidParam'
    responses: 
     '200': 
      description: null
  /PrintRequestTypes/{Who}: 
   get: 
    operationId: getPrintRequestTypes_Who
    tags: 
     - PrintRequestTypes
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/WhoParam'
     - $ref: '#/components/parameters/client_secretParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/channelidParam'
    responses: 
     '200': 
      description: Success
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/PrintRequestTypesgetResponse'
     '500': 
      description: Internal Server Error
     '404': 
      description: Not found
components: 
  schemas: 
   type: 
    type: object
    properties: 
     type: 
      type: string
     properties: 
      type: object
     type: 
      type: string
     properties: 
      type: object
     type: 
      type: string
     properties: 
      type: object
     type: 
      type: string
     properties: 
      type: object
     type: 
      type: string
     properties: 
      type: object
     type: 
      type: string
     properties: 
      type: object
     type: 
      type: string
     properties: 
      type: object
   Description: 
    type: object
    properties: 
     type: 
      type: string
     type: 
      type: string
   IsEnabled: 
    type: object
    properties: 
     type: 
      type: string
     type: 
      type: string
     type: 
      type: string
   FaqID: 
    type: object
    properties: 
     type: 
      type: string
   GroupCode: 
    type: object
    properties: 
     type: 
      type: string
     type: 
      type: string
     type: 
      type: string
   Title: 
    type: object
    properties: 
     type: 
      type: string
     type: 
      type: string
   DefaultOrder: 
    type: object
    properties: 
     type: 
      type: string
     type: 
      type: string
     type: 
      type: string
   InsertTs: 
    type: object
    properties: 
     type: 
      type: string
     type: 
      type: string
     type: 
      type: string
   LanguageType: 
    type: object
    properties: 
     type: 
      type: string
     type: 
      type: string
     type: 
      type: string
   Link: 
    type: object
    properties: 
     type: 
      type: string
     type: 
      type: string
     type: 
      type: string
   LinkText: 
    type: object
    properties: 
     type: 
      type: string
     type: 
      type: string
     type: 
      type: string
   faqsgetResponse: 
    type: object
    properties: 
     type: 
      type: object
      $ref: '#/components/schemas/type'
   Is90DayRetail: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   IsEGWP: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
   Address: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   NABP: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   PreferenceType: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   Name: 
    type: object
    properties: 
     type: 
      type: string
   IsEIC: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   PharmacyId: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   IsPreferred: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   ChainCode: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   Year: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
   Phone: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   IsPreferredCC: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   IsBrokerPbp: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   PharmacyTypeId: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   IsPrimary: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   IsEPrescribing: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   MemberPharmacyID: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   Distance: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   pharmacygetResponse: 
    type: object
    properties: 
     type: 
      type: object
      $ref: '#/components/schemas/type'
   FaultException: 
    type: object
    properties: 
     Errors: 
      type: string
     Messages: 
      type: string
     Exceptions: 
      type: string
     Warnings: 
      type: string
     Success: 
      type: string
     Errors: 
      type: string
     Messages: 
      type: string
     Exceptions: 
      type: string
     Warnings: 
      type: string
     Success: 
      type: string
     Errors: 
      type: string
     Messages: 
      type: string
     Exceptions: 
      type: string
     Warnings: 
      type: string
     Success: 
      type: string
     Errors: 
      type: string
     Messages: 
      type: string
     Exceptions: 
      type: string
     Warnings: 
      type: string
     Success: 
      type: string
   memberputResponse: 
    type: object
    properties: 
     FaultException: 
      type: object
      $ref: '#/components/schemas/FaultException'
     ResponseDetails: 
      type: string
   TenantId: 
    type: object
    properties: 
     type: 
      type: string
   TenantIdentifier: 
    type: object
    properties: 
     type: 
      type: string
   SessionTimeout: 
    type: object
    properties: 
     type: 
      type: string
   TenantName: 
    type: object
    properties: 
     type: 
      type: string
   LandingController: 
    type: object
    properties: 
     type: 
      type: string
   FolderName: 
    type: object
    properties: 
     type: 
      type: string
   HostName: 
    type: object
    properties: 
     type: 
      type: string
   LandingAction: 
    type: object
    properties: 
     type: 
      type: string
   Logo: 
    type: object
    properties: 
     type: 
      type: string
   WelcomeText: 
    type: object
    properties: 
     type: 
      type: string
   MetaDatagetResponse: 
    type: object
    properties: 
     type: 
      type: object
      $ref: '#/components/schemas/type'
   PreEnrollmentRequestpostResponse: 
    type: object
    properties: 
     FaultException: 
      type: object
      $ref: '#/components/schemas/FaultException'
     ResponseDetails: 
      type: object
      $ref: '#/components/schemas/ResponseDetails'
   ResponseDetails: 
    type: object
    properties: 
     CallExportDate: 
      type: string
     ReferralCode: 
      type: string
     RequestID: 
      type: string
     CostcoState: 
      type: string
     ModifiedDate: 
      type: string
     FollowUpDate: 
      type: string
     Enrolled: 
      type: string
     Phone: 
      type: string
     SendPacket: 
      type: string
     EntryLocation: 
      type: string
     Spanish: 
      type: string
     FollowUp: 
      type: string
     MI: 
      type: string
     Notes: 
      type: string
     ExportDate: 
      type: string
     FirstName: 
      type: string
     ZipCode: 
      type: string
     Address2: 
      type: string
     Address1: 
      type: string
     City: 
      type: string
     FollowUpName: 
      type: string
     CostcoCity: 
      type: string
     NoCallBack: 
      type: string
     State: 
      type: string
     RequestLocation: 
      type: string
     CreatedDate: 
      type: string
     Representative: 
      type: string
     LastName: 
      type: string
     RequestType: 
      type: string
     ExportDate: 
      type: string
     DrugStrength: 
      type: string
     CoverageDeterminationId: 
      type: string
     FirstName: 
      type: string
     DrugName: 
      type: string
     ExceptionRequestType: 
      type: string
     Comments: 
      type: string
     PhysicianFax: 
      type: string
     PhysicianLastName: 
      type: string
     AltMemberId: 
      type: string
     Prefix: 
      type: string
     RequestorLastName: 
      type: string
     Type: 
      type: string
     Phone: 
      type: string
     RequestorFirstName: 
      type: string
     CreatedDate: 
      type: string
     LastName: 
      type: string
     MI: 
      type: string
     PhysicianPhone: 
      type: string
     Requestor: 
      type: string
     RequestorPhone: 
      type: string
     PhysicianFirstName: 
      type: string
   WebDocumentId: 
    type: object
    properties: 
     type: 
      type: string
   DocumentType: 
    type: object
    properties: 
     type: 
      type: string
   SubGroupCode: 
    type: object
    properties: 
     type: 
      type: string
   webdocumentsgetResponse: 
    type: object
    properties: 
     type: 
      type: object
      $ref: '#/components/schemas/type'
   Deductible: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   PlanYearStages: 
    type: object
    properties: 
     type: 
      type: string
     items: 
      type: object
      $ref: '#/components/schemas/items'
     required: 
      type: string
   items: 
    type: object
    properties: 
     type: 
      type: string
     type: 
      type: string
   PlanId: 
    type: object
    properties: 
     type: 
      type: string
   StateName: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   DeductibleDescription: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   Deminimis: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   Premium: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   PlanName: 
    type: object
    properties: 
     type: 
      type: string
   PlanDetails: 
    type: object
    properties: 
     type: 
      type: string
     items: 
      type: object
      $ref: '#/components/schemas/items'
     required: 
      type: string
   GroupId: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   PbpDescription: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   Lis50: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   Lis75: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   State: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   Lis100: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   Lis25: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   PlanYear: 
    type: object
    properties: 
     type: 
      type: string
   SkipDeductable: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   Pbp: 
    type: object
    properties: 
     type: 
      type: string
     type: 
      type: string
   plangetResponse: 
    type: object
    properties: 
     type: 
      type: object
      $ref: '#/components/schemas/type'
   Gpi: 
    type: object
    properties: 
     type: 
      type: string
   UsualDailyDose: 
    type: object
    properties: 
     type: 
      type: string
   DosageFormDecoded: 
    type: object
    properties: 
     type: 
      type: string
   Tier: 
    type: object
    properties: 
     type: 
      type: string
   DrugName: 
    type: object
    properties: 
     type: 
      type: string
   PkgSize: 
    type: object
    properties: 
     format: 
      type: string
     type: 
      type: string
   ProdName: 
    type: object
    properties: 
     type: 
      type: string
   FormularyDetailId: 
    type: object
    properties: 
     type: 
      type: string
   Ndc: 
    type: object
    properties: 
     type: 
      type: string
   DosageForm: 
    type: object
    properties: 
     type: 
      type: string
   FormularyNamepostResponse: 
    type: object
    properties: 
     type: 
      type: object
      $ref: '#/components/schemas/type'
   PrintRequestpostResponse: 
    type: object
    properties: 
     PrintRequestId: 
      type: string
   GlossaryID: 
    type: object
    properties: 
     type: 
      type: string
   glossarygetResponse: 
    type: object
    properties: 
     type: 
      type: object
      $ref: '#/components/schemas/type'
   ContactpostResponse: 
    type: object
    properties: 
     FaultException: 
      type: object
      $ref: '#/components/schemas/FaultException'
     ResponseDetails: 
      type: string
   PrintRequestTypesgetResponse: 
    type: object
    properties: 
     RequestTypes: 
      type: string
   CoverageDeterminationpostResponse: 
    type: object
    properties: 
     FaultException: 
      type: object
      $ref: '#/components/schemas/FaultException'
     ResponseDetails: 
      type: object
      $ref: '#/components/schemas/ResponseDetails'
  parameters: 
   client_secretParam: 
    in: header
    name: client_secret
    required: true
    schema: 
     type: string
    description: description of parameter passed
   client_idParam: 
    in: header
    name: client_id
    required: true
    schema: 
     type: string
    description: description of parameter passed
   channelidParam: 
    in: header
    name: channelid
    required: false
    schema: 
     type: string
     format: integer | nil
    description: description of parameter passed
   TenantIdentifierParam: 
    in: header
    name: TenantIdentifier
    required: true
    schema: 
     type: string
    description: Tenant Identifier
   languageTypeParam: 
    in: path
    name: languageType
    required: true
    schema: 
     type: string
    description: string
   WhoParam: 
    in: path
    name: Who
    required: true
    schema: 
     type: string
    description: Who
