swagger: "2.0"
info: 
  title: Items API V1
  description: Items API
  version: 1.0.1
host: www.apiexample.com
basePath: /v1
schemes: 
  - https
security: 
  - BasicAuth: []
paths: 
  /items/{id}: 
   get: 
    tags: 
     - items
    description: get Item details by Id
    produces: 
     - application/json
     - application/xml
    parameters: 
     - $ref: '#/parameters/idParam'
     - $ref: '#/parameters/entityIdParam'
     - $ref: '#/parameters/clientURNParam'
     - $ref: '#/parameters/applianceTokenParam'
     - $ref: '#/parameters/systemCodeParam'
     - $ref: '#/parameters/countryCodeParam'
     - $ref: '#/parameters/clientCodeParam'
     - $ref: '#/parameters/clientGroupCodeParam'
     - $ref: '#/parameters/channelCodeParam'
     - $ref: '#/parameters/clientUserIdParam'
     - $ref: '#/parameters/clientPasswordParam'
    responses: 
     '200': 
      description: Success
      schema: 
       $ref: '#/definitions/GetItemDetailsResp'
   put: 
    tags: 
     - items
    description: updates an item by Id
    produces: 
     - application/json
     - application/xml
    parameters: 
     - $ref: '#/parameters/idParam'
     - $ref: '#/parameters/entityIdParam'
     - $ref: '#/parameters/clientURNParam'
     - $ref: '#/parameters/applianceTokenParam'
     - $ref: '#/parameters/systemCodeParam'
     - $ref: '#/parameters/countryCodeParam'
     - $ref: '#/parameters/clientCodeParam'
     - $ref: '#/parameters/clientGroupCodeParam'
     - $ref: '#/parameters/channelCodeParam'
     - $ref: '#/parameters/clientUserIdParam'
     - $ref: '#/parameters/clientPasswordParam'
     - name: UpdateItemReq
       in: body
       description: description of parameter passed
       required: true
       schema: 
        $ref: '#/definitions/UpdateItemReq'
    responses: 
     '200': 
      description: Success
      schema: 
       $ref: '#/definitions/UpdateItemResp'
      schema: 
       $ref: '#/definitions/Error'
  /items: 
   post: 
    tags: 
     - items
    description: creates Item
    produces: 
     - application/json
     - application/xml
    parameters: 
     - $ref: '#/parameters/entityIdParam'
     - $ref: '#/parameters/clientURNParam'
     - $ref: '#/parameters/applianceTokenParam'
     - $ref: '#/parameters/systemCodeParam'
     - $ref: '#/parameters/countryCodeParam'
     - $ref: '#/parameters/clientCodeParam'
     - $ref: '#/parameters/clientGroupCodeParam'
     - $ref: '#/parameters/channelCodeParam'
     - $ref: '#/parameters/clientUserIdParam'
     - $ref: '#/parameters/clientPasswordParam'
     - name: CreateItemReq
       in: body
       description: description of parameter passed
       required: true
       schema: 
        $ref: '#/definitions/CreateItemReq'
    responses: 
     '200': 
      description: Success
      schema: 
       $ref: '#/definitions/CreateItemResp'
definitions: 
   ItemDetails: 
    type: object
    properties: 
     ItemCode: 
      type: string
     ItemCodeDescription: 
      type: string
     ManufacturerBrandCode: 
      type: string
     ManufacturerBrandDescription: 
      type: string
     GoodsColour: 
      type: string
     ModelNumber: 
      type: string
     SerialNumber: 
      type: string
     OperationalStatusCode: 
      type: string
     DGAllocatedSupplierAgentCode: 
      type: string
     DGAllocatedSupplierBranchCode: 
      type: string
     LastServiceDate: 
      type: string
     LastServiceTime: 
      type: string
     ItemCatCode: 
      type: string
     ManufacturerBrandGroupCode: 
      type: string
     ItemID: 
      type: object
      $ref: '#/definitions/ItemID'
     ItemURNList: 
      type: object
      $ref: '#/definitions/ItemURNList'
     Item: 
      type: object
      $ref: '#/definitions/Item'
   AdditionalDetails: 
    type: object
    properties: 
     BoilerType: 
      type: string
     ExtCovPrdFee: 
      type: string
     PdNettFlg: 
      type: string
     CallSource: 
      type: string
     PeriodOfCover: 
      type: string
     GoodsColour: 
      type: string
     CoverType: 
      type: string
     BreakdownStartDate: 
      type: string
   Cover: 
    type: object
    properties: 
     ManufacturerGuaranteeLabourMonths: 
      type: string
     ManufacturerGuaranteePartsMonths: 
      type: string
     ThirdPartyGuaranteeLabourMonths: 
      type: string
     ThirdPartyGuaranteePartsMonths: 
      type: string
   Purchase: 
    type: object
    properties: 
     PurchasePrice: 
      type: string
     PriceCurrencyCode: 
      type: string
     PurchaseDate: 
      type: string
     PurchaseTime: 
      type: string
     RecommendedPrice: 
      type: string
     RecommendedPriceCurrencyCode: 
      type: string
     PurchaseRetailer: 
      type: string
   PersonOwnerList: 
    type: object
    properties: 
     PersonOwner: 
      type: object
      $ref: '#/definitions/PersonOwner'
   PersonOwner: 
    type: object
    properties: 
     PreviousClientURN: 
      type: string
     ClientURN: 
      type: string
     PreviousEID: 
      type: string
     EID: 
      type: string
     SrcCode: 
      type: string
   PersonUserList: 
    type: object
    properties: 
     PersonUser: 
      type: object
      $ref: '#/definitions/PersonUser'
   PersonUser: 
    type: object
    properties: 
     PreviousClientURN: 
      type: string
     ClientURN: 
      type: string
     PreviousEID: 
      type: string
     EID: 
      type: string
     SrcCode: 
      type: string
   Source: 
    type: object
    properties: 
     ChannelCode: 
      type: string
     ChannelGroupCode: 
      type: string
     SystemCode: 
      type: string
     CountryCode: 
      type: string
     ClientCode: 
      type: string
     ClientCodeDescription: 
      type: string
     ClientGroupCode: 
      type: string
     ClientGroupDescription: 
      type: string
   SourceID: 
    type: object
    properties: 
     ClientUserId: 
      type: string
     Password: 
      type: string
   GetItemDetailsResp: 
    type: object
    properties: 
     Source: 
      type: object
      $ref: '#/definitions/Source'
     ItemDetailsList: 
      type: object
      $ref: '#/definitions/ItemDetailsList'
     ErrorResponseList: 
      type: object
      $ref: '#/definitions/ErrorResponseList'
   CreateItemReq: 
    type: object
    properties: 
     SourceEvent: 
      type: object
      $ref: '#/definitions/SourceEvent'
     IsItemOwned: 
      type: string
     ItemID: 
      type: object
      $ref: '#/definitions/ItemID'
     ItemURN: 
      type: object
      $ref: '#/definitions/ItemURN'
     Item: 
      type: object
      $ref: '#/definitions/Item'
     RegisterMailer: 
      type: string
     ItemGetPriceDetails: 
      type: object
      $ref: '#/definitions/ItemGetPriceDetails'
     CustomerToken: 
      type: string
     PersonEID: 
      type: string
     MailerDetails: 
      type: object
      $ref: '#/definitions/MailerDetails'
   SourceEvent: 
    type: object
    properties: 
     BusinessEventSourceCode: 
      type: string
     BusinessEventCode: 
      type: string
     ReceivedDate: 
      type: string
     ReceivedTime: 
      type: string
     LogonUserId: 
      type: string
   ItemGetPriceDetails: 
    type: object
    properties: 
     ItemCreateOffer: 
      type: string
     GetPriceCallSourceList: 
      type: object
      $ref: '#/definitions/GetPriceCallSourceList'
   GetPriceCallSourceList: 
    type: object
    properties: 
     CallSource: 
      type: string
   MailerDetails: 
    type: object
    properties: 
     RegCode: 
      type: string
     ProdQTypeID: 
      type: string
     BoilerType: 
      type: string
     Language: 
      type: string
   Address: 
    type: object
    properties: 
     AddressCategory: 
      type: string
     AddressOverride: 
      type: string
     AddressStatus: 
      type: string
     AddressDetails: 
      type: object
      $ref: '#/definitions/AddressDetails'
   AddressDetails: 
    type: object
    properties: 
     AddressLine1: 
      type: string
     AddressLine2: 
      type: string
     AddressLine3: 
      type: string
     AddressLine4: 
      type: string
     PostalCode: 
      type: string
     CountryCode: 
      type: string
   CreateItemResp: 
    type: object
    properties: 
     ItemID: 
      type: object
      $ref: '#/definitions/ItemID'
     ItemURN: 
      type: object
      $ref: '#/definitions/ItemURN'
     Mailer: 
      type: object
      $ref: '#/definitions/Mailer'
     RTPOfferReferenceList: 
      type: object
      $ref: '#/definitions/RTPOfferReferenceList'
     RTPRateList: 
      type: object
      $ref: '#/definitions/RTPRateList'
     AlternativeApplianceList: 
      type: object
      $ref: '#/definitions/AlternativeApplianceList'
     ErrorResponseList: 
      type: object
      $ref: '#/definitions/ErrorResponseList'
   Mailer: 
    type: object
    properties: 
     CompanyCode: 
      type: string
     SchemeCode: 
      type: string
     Reference: 
      type: string
   RTPOfferReferenceList: 
    type: object
    properties: 
     RTPOfferReference: 
      type: object
      $ref: '#/definitions/RTPOfferReference'
   ItemDetailsList: 
    type: object
    properties: 
     ItemDetails: 
      type: object
      $ref: '#/definitions/ItemDetails'
   RTPOfferReference: 
    type: object
    properties: 
     OfferReference: 
      type: string
     OfferKey: 
      type: string
     CallSource: 
      type: string
   RTPRateList: 
    type: object
    properties: 
     RTPRate: 
      type: object
      $ref: '#/definitions/RTPRate'
   RTPRate: 
    type: object
    properties: 
     CallSourceDetails: 
      type: object
      $ref: '#/definitions/CallSourceDetails'
     RTPOfferDetails: 
      type: object
      $ref: '#/definitions/RTPOfferDetails'
   CallSourceDetails: 
    type: object
    properties: 
     CallSource: 
      type: string
     CallSourceDescription: 
      type: string
     Scheme: 
      type: object
      $ref: '#/definitions/Scheme'
     Agent: 
      type: object
      $ref: '#/definitions/Agent'
     ItemCode: 
      type: string
     ItemCodeDescription: 
      type: string
     PriceBand: 
      type: string
     NumberOfItems: 
      type: string
     CoverType: 
      type: string
     BreakdownStartDate: 
      type: string
     ContractType: 
      type: object
      $ref: '#/definitions/ContractType'
   Scheme: 
    type: object
    properties: 
     CompanyCode: 
      type: string
     SchemeCode: 
      type: string
     TelRegMakerCode: 
      type: string
   Agent: 
    type: object
    properties: 
     AgentNumber: 
      type: string
     SchemeCodeBranchNumber: 
      type: string
   ContractType: 
    type: object
    properties: 
     ProductCategory: 
      type: string
     ProductCategoryDesc: 
      type: string
     ProductType: 
      type: string
     ProductTypeDesc: 
      type: string
     ProductVariance: 
      type: string
     ProductVarianceDesc: 
      type: string
     PaymentTerm: 
      type: string
     PaymentTermDesc: 
      type: string
     ContractTypeCode: 
      type: string
     ContractTypeDesc: 
      type: string
     ProductDescription: 
      type: string
   RTPOfferDetails: 
    type: object
    properties: 
     OfferReference: 
      type: string
     OfferKey: 
      type: string
     OfferPricingKey: 
      type: string
     PeriodOfCover: 
      type: string
     Fee: 
      type: string
     WaitDays: 
      type: string
     WicType: 
      type: string
     MultiplanType: 
      type: string
     MultiplanWarrantyType: 
      type: string
     RTPPaymentDetails: 
      type: object
      $ref: '#/definitions/RTPPaymentDetails'
   RTPPaymentDetails: 
    type: object
    properties: 
     PreferredPayment: 
      type: string
     PaymentType: 
      type: string
     PaymentProfile: 
      type: string
     CashPaymentType: 
      type: string
     NumberOfPayments: 
      type: string
     PaymentFrequency: 
      type: string
     FirstPayment: 
      type: string
     SubsequentPayment: 
      type: string
     ExcessAmount: 
      type: string
     RTPRates: 
      type: object
      $ref: '#/definitions/RTPRates'
   RTPRates: 
    type: object
    properties: 
     OfferPricingDetailsKey: 
      type: string
     LevelOfCover: 
      type: string
     ItemCode: 
      type: string
     PayProfile: 
      type: string
     PeriodOfCover: 
      type: string
     ServiceFee: 
      type: string
     Price: 
      type: string
     NetFee: 
      type: string
     GrossFee: 
      type: string
     TotalPrice: 
      type: string
     InsPremTax: 
      type: string
     SumInsured: 
      type: string
     ExcessValue: 
      type: string
     ClientMargin: 
      type: string
     ManuMargin: 
      type: string
     Procurement: 
      type: string
     UnderWrtPrem: 
      type: string
     IPTTaxRate: 
      type: string
     PriceBand: 
      type: string
     RetroMargin: 
      type: string
     RetraOvr: 
      type: string
     ManufOvr: 
      type: string
     SalesStaffInc: 
      type: string
     CoverCode: 
      type: string
     ExclusionCode: 
      type: string
     Underwriter: 
      type: string
     ReserveCode: 
      type: string
     ReservePOC: 
      type: string
     ReserveMfGuar: 
      type: string
   AlternativeApplianceList: 
    type: object
    properties: 
     AlternativeAppliance: 
      type: object
      $ref: '#/definitions/AlternativeAppliance'
   AlternativeAppliance: 
    type: object
    properties: 
     CompanyCode: 
      type: string
     SchemeCode: 
      type: string
     ItemGroupCode: 
      type: string
     ItemCode: 
      type: string
     ItemDescription: 
      type: string
   UpdateItemReq: 
    type: object
    properties: 
     SourceEvent: 
      type: object
      $ref: '#/definitions/SourceEvent'
     ItemID: 
      type: object
      $ref: '#/definitions/ItemID'
     ItemURN: 
      type: object
      $ref: '#/definitions/ItemURN'
     Item: 
      type: object
      $ref: '#/definitions/Item'
     Plan: 
      type: object
      $ref: '#/definitions/Plan'
     IsNewBabyPlan: 
      type: string
     NewBabyPlanList: 
      type: object
      $ref: '#/definitions/NewBabyPlanList'
     Mailer: 
      type: object
      $ref: '#/definitions/Mailer'
     UpdateMailerStatus: 
      type: string
     CustomerToken: 
      type: string
     OvrBabyBSD: 
      type: string
   Plan: 
    type: object
    properties: 
     CompanyCode: 
      type: string
     SchemeCode: 
      type: string
     Reference: 
      type: string
   NewBabyPlanList: 
    type: object
    properties: 
     NewBabyPlan: 
      type: object
      $ref: '#/definitions/NewBabyPlan'
   NewBabyPlan: 
    type: object
    properties: 
     ItemID: 
      type: object
      $ref: '#/definitions/ItemID'
     ItemURN: 
      type: object
      $ref: '#/definitions/ItemURN'
     Mailer: 
      type: object
      $ref: '#/definitions/Mailer'
     Item: 
      type: object
      $ref: '#/definitions/Item'
   UpdateItemResp: 
    type: object
    properties: 
     ItemID: 
      type: object
      $ref: '#/definitions/ItemID'
     ItemURN: 
      type: object
      $ref: '#/definitions/ItemURN'
     BabyPlanList: 
      type: object
      $ref: '#/definitions/BabyPlanList'
     ErrorResponseList: 
      type: object
      $ref: '#/definitions/ErrorResponseList'
   BabyPlan: 
    type: object
    properties: 
     CompanyCode: 
      type: string
     SchemeCode: 
      type: string
     Reference: 
      type: string
     ItemCode: 
      type: string
     ModelNumber1: 
      type: string
     ModelNumber2: 
      type: string
     ErrorMessage: 
      type: string
   ErrorResponseList: 
    type: object
    properties: 
     Error: 
      type: object
      $ref: '#/definitions/Error'
   Error: 
    type: object
    properties: 
     ErrorCode: 
      type: string
     ErrorDescription: 
      type: string
   ItemID: 
    type: object
    properties: 
     EID: 
      type: string
   BabyPlanList: 
    type: object
    properties: 
     BabyPlan: 
      type: object
      $ref: '#/definitions/BabyPlan'
   OtherIds: 
    type: object
    properties: 
     OtherId1: 
      type: string
     OtherId1CategoryCode: 
      type: string
     OtherId2: 
      type: string
     OtherId2CategoryCode: 
      type: string
     OtherId3: 
      type: string
     OtherId3CategoryCode: 
      type: string
     OtherModelId1: 
      type: string
     OtherModelId1CategoryCode: 
      type: string
     OtherModelId2: 
      type: string
     OtherModelId2CategoryCode: 
      type: string
   ItemURNList: 
    type: object
    properties: 
     ItemURN: 
      type: object
      $ref: '#/definitions/ItemURN'
   ItemURN: 
    type: object
    properties: 
     ClientURN: 
      type: string
     ApplianceToken: 
      type: string
   Item: 
    type: object
    properties: 
     ItemLink: 
      type: object
      $ref: '#/definitions/ItemLink'
     ItemDetails: 
      type: object
      $ref: '#/definitions/ItemDetails'
     AdditionalDetails: 
      type: object
      $ref: '#/definitions/AdditionalDetails'
     OtherIds: 
      type: object
      $ref: '#/definitions/OtherIds'
     Cover: 
      type: object
      $ref: '#/definitions/Cover'
     Purchase: 
      type: object
      $ref: '#/definitions/Purchase'
     Address: 
      type: object
      $ref: '#/definitions/Address'
     PersonOwnerList: 
      type: object
      $ref: '#/definitions/PersonOwnerList'
     PersonUserList: 
      type: object
      $ref: '#/definitions/PersonUserList'
     ClientCode: 
      type: string
     ItemCtgCode: 
      type: string
   ItemLink: 
    type: object
    properties: 
     MemIdNum: 
      type: string
     SrcCode: 
      type: string
parameters: 
   idParam: 
    in: path
    name: id
    type: string
    required: true
    description: Id of an item to get details
   entityIdParam: 
    in: header
    name: entityId
    type: string
    required: true
    description: description of parameter passed
   clientURNParam: 
    in: header
    name: clientURN
    type: string
    required: true
    description: description of parameter passed
   applianceTokenParam: 
    in: header
    name: applianceToken
    type: string
    required: true
    description: description of parameter passed
   systemCodeParam: 
    in: header
    name: systemCode
    type: string
    required: true
    description: description of parameter passed
   countryCodeParam: 
    in: header
    name: countryCode
    type: string
    required: true
    description: description of parameter passed
   clientCodeParam: 
    in: header
    name: clientCode
    type: string
    required: true
    description: description of parameter passed
   clientGroupCodeParam: 
    in: header
    name: clientGroupCode
    type: string
    required: true
    description: description of parameter passed
   channelCodeParam: 
    in: header
    name: channelCode
    type: string
    required: true
    description: description of parameter passed
   clientUserIdParam: 
    in: header
    name: clientUserId
    type: string
    required: true
    description: description of parameter passed
   clientPasswordParam: 
    in: header
    name: clientPassword
    type: string
    required: true
    description: description of parameter passed
securityDefinitions: 
   BasicAuth: 
    type: basic
