openapi: 3.0.0
info: 
  version: 1.0.0
  title: EIC-Admin-Exp-Api
  description: API description
servers: 
  - url: api
    description: API Server Description
paths: 
  /member: 
   post: 
    operationId: postmember
    tags: 
     - member
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/memberInsertRequest'
    parameters: 
     - $ref: '#/components/parameters/TenantIdentifierParam'
     - $ref: '#/components/parameters/client_secretParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/channelidParam'
    responses: 
     '200': 
      description: Success
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/memberpostResponse'
     '500': 
      description: Success
      content: 
       application/json: 
                                                    schema:
                                                     type: string
components: 
  schemas: 
   FaultException: 
    type: object
    properties: 
     Errors: 
      type: string
     Messages: 
      type: string
     Exceptions: 
      type: string
     Warnings: 
      type: string
     Success: 
      type: string
   memberpostResponse: 
    type: object
    properties: 
     FaultException: 
      type: object
      $ref: '#/components/schemas/FaultException'
     ResponseDetails: 
      type: object
      $ref: '#/components/schemas/ResponseDetails'
   ResponseDetails: 
    type: object
    properties: 
     PaymentException: 
      type: string
     SsaDeductRequested: 
      type: string
     ProcessPaymentReponse: 
      type: string
     IsBrokerCompliant: 
      type: string
     Member: 
      type: object
      $ref: '#/components/schemas/Member'
   Member: 
    type: object
    properties: 
     MZipCode: 
      type: string
     Email: 
      type: string
     GreenEobReasonCode: 
      type: string
     MCity: 
      type: string
     BWritingCode: 
      type: string
     BrokerID: 
      type: string
     CellPhone: 
      type: string
     CurrentBalance: 
      type: string
     AltMemberId: 
      type: string
     Prefix: 
      type: string
     Gender: 
      type: string
     PlanName: 
      type: string
     PbpId: 
      type: string
     HICN: 
      type: string
     MemberId: 
      type: string
     MailNABPs: 
      type: string
     EnrollmentDate: 
      type: string
     MiddleInitial: 
      type: string
     MBI: 
      type: string
     DOB: 
      type: string
     Phone: 
      type: string
     BrokerAttestation: 
      type: string
     PbpCode: 
      type: string
     DisenrollmentDate: 
      type: string
     MAddress2: 
      type: string
     Status: 
      type: string
     MAddress1: 
      type: string
     PrimaryPharmacy: 
      type: string
     FirstName: 
      type: string
     ZipCode: 
      type: string
     PlanId: 
      type: string
     Address2: 
      type: string
     MState: 
      type: string
     Address1: 
      type: string
     City: 
      type: string
     GroupId: 
      type: string
     Pharmacies: 
      type: string
     MedicareNumber: 
      type: string
     MonthlyPremium: 
      type: string
     AltPhone: 
      type: string
     CMSConfirmationID: 
      type: string
     Year: 
      type: string
     State: 
      type: string
     LastName: 
      type: string
     EGWPDirectBill: 
      type: string
     IsBroker: 
      type: string
   memberInsertRequest: 
    type: object
    properties: 
     ReferralCode: 
      type: string
     Email: 
      type: string
     Address: 
      type: object
      $ref: '#/components/schemas/Address'
     Gender: 
      type: string
     MiddleInitial: 
      type: string
     DateOfBirth: 
      type: string
     CmsConfirmationId: 
      type: string
     AltPhone: 
      type: string
     LastName: 
      type: string
     ApplicationId: 
      type: string
     CellPhone: 
      type: string
     SepReason: 
      type: string
     Prefix: 
      type: string
     ApplicationDate: 
      type: string
     OtherCoverage: 
      type: object
     Language: 
      type: string
     Phone: 
      type: string
     altFormatRqst: 
      type: string
     Broker: 
      type: object
     ZipCode: 
      type: string
     StateCode: 
      type: string
     MailingAddress: 
      type: object
     Plan: 
      type: object
     SeparationReasonDescription: 
      type: string
     GroupId: 
      type: string
     Firstname: 
      type: string
     MedicareNumber: 
      type: string
     ElectionType: 
      type: string
     BrokerAttestationType: 
      type: string
     Representative: 
      type: object
   ZipCode: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
     required: 
      type: string
   Address2: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
     required: 
      type: string
   StateCode: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
     required: 
      type: string
   Address1: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
     required: 
      type: string
   City: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
     required: 
      type: string
   Group: 
    type: object
    properties: 
     type: 
      type: string
   Id: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
     required: 
      type: string
   Name: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
     required: 
      type: string
   DateOfBirth: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   Status: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
     enum: 
      type: string
   Email: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
     required: 
      type: string
   LicenseExpirationDate: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   Address: 
    type: object
    properties: 
     type: 
      type: string
     properties: 
      type: object
     required: 
      type: string
     type: 
      type: string
     properties: 
      type: object
     required: 
      type: string
   FirstName: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   AgentSuspended: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   NPN: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   SSN: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   LicenseState: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   Referral: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   Phone: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
   LicenseStatus: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   Relationship: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
   LastName: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   WritingCode: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   MailAddress1: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   Deductible: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   IsEGWP: 
    type: object
    properties: 
     type: 
      type: string
   PlanYearStages: 
    type: object
    properties: 
     type: 
      type: string
     items: 
      type: object
      $ref: '#/components/schemas/items'
     required: 
      type: string
   items: 
    type: object
    properties: 
     type: 
      type: string
     type: 
      type: string
   PlanId: 
    type: object
    properties: 
     format: 
      type: string
     type: 
      type: string
   StateName: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   DeductibleDescription: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   Deminimis: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   Premium: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   PlanName: 
    type: object
    properties: 
     type: 
      type: string
   PlanDetails: 
    type: object
    properties: 
     type: 
      type: string
     items: 
      type: object
      $ref: '#/components/schemas/items'
     required: 
      type: string
   GroupId: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   PbpDescription: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   Lis50: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   Lis75: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   State: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   Lis100: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   Lis25: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   PlanYear: 
    type: object
    properties: 
     format: 
      type: string
     type: 
      type: string
   SkipDeductable: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   Pbp: 
    type: object
    properties: 
     type: 
      type: string
  parameters: 
   TenantIdentifierParam: 
    in: header
    name: TenantIdentifier
    required: false
    schema: 
     type: string
    description: Tenant Identifier
   client_secretParam: 
    in: header
    name: client_secret
    required: true
    schema: 
     type: string
    description: description of parameter passed
   client_idParam: 
    in: header
    name: client_id
    required: true
    schema: 
     type: string
    description: description of parameter passed
   channelidParam: 
    in: header
    name: channelid
    required: false
    schema: 
     type: string
     format: integer | nil
    description: Unique Id to determine the Client
