openapi: 3.0.0
info: 
  version: 1.0.0
  title: EIC-Admin-Exp-Api
  description: API description
servers: 
  - url: api
    description: API Server Description
paths: 
  /SSADeductByMemberID/{memberId}: 
   get: 
    operationId: getSSADeductByMemberID_memberId
    tags: 
     - SSADeductByMemberID
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/memberIdParam'
     - $ref: '#/components/parameters/TenantIdentifierParam'
     - $ref: '#/components/parameters/client_secretParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/channelidParam'
    responses: 
     '200': 
      description: Success
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/SSADeductByMemberIDgetResponse'
     '500': 
      description: Success
      content: 
       application/json: 
  /member: 
   post: 
    operationId: postmember
    tags: 
     - member
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/TenantIdentifierParam'
     - $ref: '#/components/parameters/client_secretParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/channelidParam'
    responses: 
     '200': 
      description: Success
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/memberpostResponse'
     '500': 
      description: Success
      content: 
       application/json: 
   get: 
    operationId: getmember
    tags: 
     - member
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/TenantIdentifierParam'
     - $ref: '#/components/parameters/memberIdQueryParam'
     - $ref: '#/components/parameters/client_secretParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/channelidParam'
    responses: 
     '200': 
      description: Success
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/membergetResponse'
     '500': 
      description: Internal Server Error
     '404': 
      description: Not found
   put: 
    operationId: putmember
    tags: 
     - member
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/TenantIdentifierParam'
     - $ref: '#/components/parameters/client_secretParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/channelidParam'
    responses: 
     '200': 
      description: Success
      content: 
       application/json: 
     '500': 
      description: Success
      content: 
       application/json: 
components: 
  schemas: 
   SSADeductByMemberIDResponse: 
    type: object
    properties: 
     SSADeductID: 
      type: string
     ExportDate: 
      type: string
     MemberID: 
      type: string
     CreatedBy: 
      type: string
     NameID: 
      type: string
     FirstName: 
      type: string
     CreatedDate: 
      type: string
     ExportedBy: 
      type: string
     LastName: 
      type: string
     MedicareID: 
      type: string
   FaultException: 
    type: object
    properties: 
     Errors: 
      type: string
     Messages: 
      type: string
     Exceptions: 
      type: string
     Warnings: 
      type: string
     Success: 
      type: string
   memberpostResponse: 
    type: object
    properties: 
     FaultException: 
      type: object
      $ref: '#/components/schemas/FaultException'
     ResponseDetails: 
      type: object
      $ref: '#/components/schemas/ResponseDetails'
   ResponseDetails: 
    type: object
    properties: 
     PaymentException: 
      type: string
     SsaDeductRequested: 
      type: string
     ProcessPaymentReponse: 
      type: string
     IsBrokerCompliant: 
      type: string
     Member: 
      type: object
      $ref: '#/components/schemas/Member'
   Member: 
    type: object
    properties: 
     MZipCode: 
      type: string
     Email: 
      type: string
     GreenEobReasonCode: 
      type: string
     MCity: 
      type: string
     BWritingCode: 
      type: string
     BrokerID: 
      type: string
     CellPhone: 
      type: string
     CurrentBalance: 
      type: string
     AltMemberId: 
      type: string
     Prefix: 
      type: string
     Gender: 
      type: string
     PlanName: 
      type: string
     PbpId: 
      type: string
     HICN: 
      type: string
     MemberId: 
      type: string
     MailNABPs: 
      type: string
     EnrollmentDate: 
      type: string
     MiddleInitial: 
      type: string
     MBI: 
      type: string
     DOB: 
      type: string
     Phone: 
      type: string
     BrokerAttestation: 
      type: string
     PbpCode: 
      type: string
     DisenrollmentDate: 
      type: string
     MAddress2: 
      type: string
     Status: 
      type: string
     MAddress1: 
      type: string
     PrimaryPharmacy: 
      type: string
     FirstName: 
      type: string
     ZipCode: 
      type: string
     PlanId: 
      type: string
     Address2: 
      type: string
     MState: 
      type: string
     Address1: 
      type: string
     City: 
      type: string
     GroupId: 
      type: string
     Pharmacies: 
      type: string
     MedicareNumber: 
      type: string
     MonthlyPremium: 
      type: string
     AltPhone: 
      type: string
     CMSConfirmationID: 
      type: string
     Year: 
      type: string
     State: 
      type: string
     LastName: 
      type: string
     EGWPDirectBill: 
      type: string
     IsBroker: 
      type: string
   EmergencyContact: 
    type: object
    properties: 
     Phone: 
      type: string
     Relationship: 
      type: string
     Name: 
      type: string
   membergetResponse: 
    type: object
    properties: 
     EmergencyContact: 
      type: object
      $ref: '#/components/schemas/EmergencyContact'
     Address: 
      type: object
      $ref: '#/components/schemas/Address'
     Institution: 
      type: object
      $ref: '#/components/schemas/Institution'
     OtherCoverage: 
      type: object
      $ref: '#/components/schemas/OtherCoverage'
     Broker: 
      type: object
      $ref: '#/components/schemas/Broker'
     MailingAddress: 
      type: object
      $ref: '#/components/schemas/MailingAddress'
     Plan: 
      type: object
      $ref: '#/components/schemas/Plan'
     Representative: 
      type: object
      $ref: '#/components/schemas/Representative'
   memberResponse: 
    type: object
    properties: 
     Email: 
      type: string
     HasEmergencyContact: 
      type: string
     CellPhone: 
      type: string
     HasOtherCoverage: 
      type: string
     SepReasonId: 
      type: string
     Prefix: 
      type: string
     Gender: 
      type: string
     LargePrint: 
      type: string
     ApplicationDate: 
      type: string
     EnrollmentDate: 
      type: string
     MiddleInitial: 
      type: string
     Language: 
      type: string
     Phone: 
      type: string
     BrokerAttestation: 
      type: string
     EnrollmentType: 
      type: string
     PaymentType: 
      type: string
     IsLongTermCare: 
      type: string
     DeductSsa: 
      type: string
     DateOfBirth: 
      type: string
     HasBroker: 
      type: string
     PartAEffDate: 
      type: string
     PartBEffDate: 
      type: string
     GroupId: 
      type: string
     Firstname: 
      type: string
     MedicareNumber: 
      type: string
     AltPhone: 
      type: string
     ElectionType: 
      type: string
     IsRepresentative: 
      type: string
     BrokerAttestationType: 
      type: string
     LastName: 
      type: string
     Audio: 
      type: string
     IsBroker: 
      type: string
   Address: 
    type: object
    properties: 
     ZipCode: 
      type: string
     Address2: 
      type: string
     StateCode: 
      type: string
     Address1: 
      type: string
     City: 
      type: string
   Institution: 
    type: object
    properties: 
     Address: 
      type: object
      $ref: '#/components/schemas/Address'
     Phone: 
      type: string
     Relationship: 
      type: string
     Name: 
      type: string
   OtherCoverage: 
    type: object
    properties: 
     Group: 
      type: string
     Id: 
      type: string
     Name: 
      type: string
   Broker: 
    type: object
    properties: 
     Referral: 
      type: object
      $ref: '#/components/schemas/Referral'
   Referral: 
    type: object
    properties: 
     FirstName: 
      type: string
     Phone: 
      type: string
     LastName: 
      type: string
     Code: 
      type: string
   MailingAddress: 
    type: object
    properties: 
     ZipCode: 
      type: string
     Address2: 
      type: string
     StateCode: 
      type: string
     Address1: 
      type: string
     City: 
      type: string
   Plan: 
    type: object
    properties: 
     IsEGWP: 
      type: string
     PlanId: 
      type: string
     PlanYear: 
      type: string
     PlanName: 
      type: string
     Pbp: 
      type: string
   Representative: 
    type: object
    properties: 
     Address: 
      type: object
      $ref: '#/components/schemas/Address'
     Phone: 
      type: string
     Relationship: 
      type: string
     Name: 
      type: string
  parameters: 
   memberIdParam: 
    in: path
    name: memberId
    required: true
    schema: 
     type: string
    description: Unique MemberID
   TenantIdentifierParam: 
    in: header
    name: TenantIdentifier
    required: false
    schema: 
     type: string
    description: Tenant Identifier
   client_secretParam: 
    in: header
    name: client_secret
    required: true
    schema: 
     type: string
    description: description of parameter passed
   client_idParam: 
    in: header
    name: client_id
    required: true
    schema: 
     type: string
    description: description of parameter passed
   channelidParam: 
    in: header
    name: channelid
    required: false
    schema: 
     type: string
     format: integer | nil
    description: Unique Id to determine the Client
   memberIdQueryParam: 
    in: query
    name: memberIdQuery
    required: true
    schema: 
     type: integer
    description: Unique member Id
