openapi: 3.0.0
info: 
  version: 1.0.0
  title: EIC-Admin-Exp-Api
  description: API description
servers: 
  - url: api
    description: API Server Description
paths: 
  /member: 
   post: 
    operationId: postmember
    tags: 
     - member
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/memberInsertRequest'
    parameters: 
     - $ref: '#/components/parameters/TenantIdentifierParam'
     - $ref: '#/components/parameters/client_secretParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/channelidParam'
    responses: 
     '200': 
      description: Success
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/memberpostResponse'
     '500': 
      description: Success
      content: 
       application/json: 
                                                    schema:
                                                     type: string
   get: 
    operationId: getmember
    tags: 
     - member
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/memberIdQueryParam'
     - $ref: '#/components/parameters/client_secretParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/channelidParam'
    responses: 
     '200': 
      description: Success
      content: 
       application/json: 
                                                    schema:
                                                     type: string
     '500': 
      description: Internal Server Error
     '404': 
      description: Not found
   put: 
    operationId: putmember
    tags: 
     - member
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/memberUpdateRequest'
    parameters: 
     - $ref: '#/components/parameters/client_secretParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/channelidParam'
    responses: 
     '200': 
      description: Success
      content: 
       application/json: 
                                                    schema:
                                                     type: string
     '500': 
      description: Success
      content: 
       application/json: 
                                                    schema:
                                                     type: string
components: 
  schemas: 
   memberpostResponse: 
    type: object
    properties: 
     FaultException: 
      type: string
     ResponseDetails: 
      type: string
   memberInsertRequest: 
    type: object
    properties: 
     ReferralCode: 
      type: string
     Email: 
      type: string
     Gender: 
      type: string
     MiddleInitial: 
      type: string
     DateOfBirth: 
      type: string
     CmsConfirmationId: 
      type: string
     AltPhone: 
      type: string
     LastName: 
      type: string
     ApplicationId: 
      type: string
     CellPhone: 
      type: string
     SepReason: 
      type: string
     Prefix: 
      type: string
     ApplicationDate: 
      type: string
     Language: 
      type: string
     Phone: 
      type: string
     altFormatRqst: 
      type: string
     ZipCode: 
      type: string
     StateCode: 
      type: string
     SeparationReasonDescription: 
      type: string
     GroupId: 
      type: string
     Firstname: 
      type: string
     MedicareNumber: 
      type: string
     ElectionType: 
      type: string
     BrokerAttestationType: 
      type: string
   ReferralCode: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
     required: 
      type: string
   Email: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
     required: 
      type: string
   properties: 
    type: object
    properties: 
     ZipCode: 
      type: object
      $ref: '#/components/schemas/ZipCode'
     Address2: 
      type: object
      $ref: '#/components/schemas/Address2'
     StateCode: 
      type: object
      $ref: '#/components/schemas/StateCode'
     Address1: 
      type: object
      $ref: '#/components/schemas/Address1'
     City: 
      type: object
      $ref: '#/components/schemas/City'
     Group: 
      type: object
     Id: 
      type: object
      $ref: '#/components/schemas/Id'
     Name: 
      type: object
      $ref: '#/components/schemas/Name'
     DateOfBirth: 
      type: object
      $ref: '#/components/schemas/DateOfBirth'
     Status: 
      type: object
      $ref: '#/components/schemas/Status'
     Email: 
      type: object
      $ref: '#/components/schemas/Email'
     LicenseExpirationDate: 
      type: object
      $ref: '#/components/schemas/LicenseExpirationDate'
     Address: 
      type: object
      $ref: '#/components/schemas/Address'
     FirstName: 
      type: object
      $ref: '#/components/schemas/FirstName'
     AgentSuspended: 
      type: object
      $ref: '#/components/schemas/AgentSuspended'
     NPN: 
      type: object
      $ref: '#/components/schemas/NPN'
     SSN: 
      type: object
      $ref: '#/components/schemas/SSN'
     LicenseState: 
      type: object
      $ref: '#/components/schemas/LicenseState'
     Referral: 
      type: object
      $ref: '#/components/schemas/Referral'
     Phone: 
      type: object
      $ref: '#/components/schemas/Phone'
     LicenseStatus: 
      type: object
      $ref: '#/components/schemas/LicenseStatus'
     Relationship: 
      type: object
      $ref: '#/components/schemas/Relationship'
     LastName: 
      type: object
      $ref: '#/components/schemas/LastName'
     WritingCode: 
      type: object
      $ref: '#/components/schemas/WritingCode'
     MailAddress1: 
      type: object
      $ref: '#/components/schemas/MailAddress1'
     Deductible: 
      type: object
      $ref: '#/components/schemas/Deductible'
     IsEGWP: 
      type: object
     PlanYearStages: 
      type: object
      $ref: '#/components/schemas/PlanYearStages'
     PlanId: 
      type: object
      $ref: '#/components/schemas/PlanId'
     StateName: 
      type: object
      $ref: '#/components/schemas/StateName'
     DeductibleDescription: 
      type: object
      $ref: '#/components/schemas/DeductibleDescription'
     Deminimis: 
      type: object
      $ref: '#/components/schemas/Deminimis'
     Premium: 
      type: object
      $ref: '#/components/schemas/Premium'
     PlanName: 
      type: object
     PlanDetails: 
      type: object
      $ref: '#/components/schemas/PlanDetails'
     GroupId: 
      type: object
      $ref: '#/components/schemas/GroupId'
     PbpDescription: 
      type: object
      $ref: '#/components/schemas/PbpDescription'
     Lis50: 
      type: object
      $ref: '#/components/schemas/Lis50'
     Lis75: 
      type: object
      $ref: '#/components/schemas/Lis75'
     State: 
      type: object
      $ref: '#/components/schemas/State'
     Lis100: 
      type: object
      $ref: '#/components/schemas/Lis100'
     Lis25: 
      type: object
      $ref: '#/components/schemas/Lis25'
     PlanYear: 
      type: object
      $ref: '#/components/schemas/PlanYear'
     SkipDeductable: 
      type: object
      $ref: '#/components/schemas/SkipDeductable'
     Pbp: 
      type: object
   ZipCode: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
     required: 
      type: string
   Address2: 
    type: object
    properties: 
     required: 
      type: string
   StateCode: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
     required: 
      type: string
   Address1: 
    type: object
    properties: 
     required: 
      type: string
   City: 
    type: object
    properties: 
     required: 
      type: string
   Address: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
     ZipCode: 
      type: string
     Address2: 
      type: string
     StateCode: 
      type: string
     Address1: 
      type: string
     City: 
      type: string
     required: 
      type: string
   Institution: 
    type: object
    properties: 
     required: 
      type: string
     Address: 
      type: object
      $ref: '#/components/schemas/Address'
     Phone: 
      type: string
     Relationship: 
      type: string
     Name: 
      type: string
     required: 
      type: string
   MiddleInitial: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
   DateOfBirth: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
     required: 
      type: string
   PartAEffDate: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
   CmsConfirmationId: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
   spouseWorkInd: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
   LastName: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
     required: 
      type: string
   ApplicationId: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
   EmergencyContact: 
    type: object
    properties: 
     required: 
      type: string
     Phone: 
      type: string
     Relationship: 
      type: string
     Name: 
      type: string
     required: 
      type: string
   HasEmergencyContact: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
   SepReason: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
   Prefix: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
   ApplicationDate: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
   selfWorkInd: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
   Id: 
    type: object
    properties: 
     required: 
      type: string
   Name: 
    type: object
    properties: 
     required: 
      type: string
   Phone: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
     required: 
      type: string
   altFormatRqst: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
   EnrollmentType: 
    type: object
    properties: 
     format: 
      type: string
     format: 
      type: string
   PaymentType: 
    type: object
    properties: 
     format: 
      type: string
     format: 
      type: string
   IsLongTermCare: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
   Status: 
    type: object
    properties: 
     required: 
      type: string
     enum: 
      type: string
   LicenseExpirationDate: 
    type: object
    properties: 
     required: 
      type: string
   FirstName: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
     required: 
      type: string
   AgentSuspended: 
    type: object
    properties: 
     required: 
      type: string
   NPN: 
    type: object
    properties: 
     required: 
      type: string
   SSN: 
    type: object
    properties: 
     required: 
      type: string
   LicenseState: 
    type: object
    properties: 
     required: 
      type: string
   Referral: 
    type: object
    properties: 
     required: 
      type: string
     FirstName: 
      type: string
     Phone: 
      type: string
     LastName: 
      type: string
     Code: 
      type: string
   LicenseStatus: 
    type: object
    properties: 
     required: 
      type: string
   Relationship: 
    type: object
    properties: 
     required: 
      type: string
   WritingCode: 
    type: object
    properties: 
     required: 
      type: string
   MailAddress1: 
    type: object
    properties: 
     required: 
      type: string
   Broker: 
    type: object
    properties: 
     required: 
      type: string
     Referral: 
      type: object
      $ref: '#/components/schemas/Referral'
     required: 
      type: string
   LoginId: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
   MailingAddress: 
    type: object
    properties: 
     required: 
      type: string
     ZipCode: 
      type: string
     Address2: 
      type: string
     StateCode: 
      type: string
     Address1: 
      type: string
     City: 
      type: string
     required: 
      type: string
   HasBroker: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
   Deductible: 
    type: object
    properties: 
     required: 
      type: string
   items: 
    type: object
    properties: 
     type: 
      type: string
     type: 
      type: string
   PlanYearStages: 
    type: object
    properties: 
     required: 
      type: string
   PlanId: 
    type: object
    properties: 
     format: 
      type: string
   StateName: 
    type: object
    properties: 
     required: 
      type: string
   DeductibleDescription: 
    type: object
    properties: 
     required: 
      type: string
   Deminimis: 
    type: object
    properties: 
     required: 
      type: string
   Premium: 
    type: object
    properties: 
     required: 
      type: string
   PlanDetails: 
    type: object
    properties: 
     required: 
      type: string
   GroupId: 
    type: object
    properties: 
     required: 
      type: string
   PbpDescription: 
    type: object
    properties: 
     required: 
      type: string
   Lis50: 
    type: object
    properties: 
     required: 
      type: string
   Lis75: 
    type: object
    properties: 
     required: 
      type: string
   State: 
    type: object
    properties: 
     required: 
      type: string
   Lis100: 
    type: object
    properties: 
     required: 
      type: string
   Lis25: 
    type: object
    properties: 
     required: 
      type: string
   PlanYear: 
    type: object
    properties: 
     format: 
      type: string
   SkipDeductable: 
    type: object
    properties: 
     required: 
      type: string
   PartBEffDate: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
   SeparationReasonDescription: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
   Firstname: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
     required: 
      type: string
   UserId: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
   BrokerAttestationType: 
    type: object
    properties: 
     required: 
      type: string
     required: 
      type: string
   membergetResponse: 
    type: object
    properties: 
     EmergencyContact: 
      type: object
      $ref: '#/components/schemas/EmergencyContact'
     Email: 
      type: string
     Address: 
      type: object
      $ref: '#/components/schemas/Address'
     HasEmergencyContact: 
      type: string
     CellPhone: 
      type: string
     HasOtherCoverage: 
      type: string
     SepReasonId: 
      type: string
     Prefix: 
      type: string
     Gender: 
      type: string
     Institution: 
      type: object
      $ref: '#/components/schemas/Institution'
     LargePrint: 
      type: string
     ApplicationDate: 
      type: string
     EnrollmentDate: 
      type: string
     MiddleInitial: 
      type: string
     OtherCoverage: 
      type: object
      $ref: '#/components/schemas/OtherCoverage'
     Language: 
      type: string
     Phone: 
      type: string
     BrokerAttestation: 
      type: string
     EnrollmentType: 
      type: string
     PaymentType: 
      type: string
     IsLongTermCare: 
      type: string
     DeductSsa: 
      type: string
     DateOfBirth: 
      type: string
     Broker: 
      type: object
      $ref: '#/components/schemas/Broker'
     MailingAddress: 
      type: object
      $ref: '#/components/schemas/MailingAddress'
     HasBroker: 
      type: string
     Plan: 
      type: object
      $ref: '#/components/schemas/Plan'
     PartAEffDate: 
      type: string
     PartBEffDate: 
      type: string
     GroupId: 
      type: string
     Firstname: 
      type: string
     MedicareNumber: 
      type: string
     AltPhone: 
      type: string
     ElectionType: 
      type: string
     IsRepresentative: 
      type: string
     BrokerAttestationType: 
      type: string
     Representative: 
      type: object
      $ref: '#/components/schemas/Representative'
     LastName: 
      type: string
     Audio: 
      type: string
     IsBroker: 
      type: string
   OtherCoverage: 
    type: object
    properties: 
     Group: 
      type: string
     Id: 
      type: string
     Name: 
      type: string
   Plan: 
    type: object
    properties: 
     IsEGWP: 
      type: string
     PlanId: 
      type: string
     PlanYear: 
      type: string
     PlanName: 
      type: string
     Pbp: 
      type: string
   Representative: 
    type: object
    properties: 
     Address: 
      type: object
      $ref: '#/components/schemas/Address'
     Phone: 
      type: string
     Relationship: 
      type: string
     Name: 
      type: string
   memberUpdateRequest: 
    type: object
    properties: 
     ReferralCode: 
      type: string
     Email: 
      type: string
     Gender: 
      type: string
     MiddleInitial: 
      type: string
     DateOfBirth: 
      type: string
     CmsConfirmationId: 
      type: string
     AltPhone: 
      type: string
     LastName: 
      type: string
     ApplicationId: 
      type: string
     CellPhone: 
      type: string
     SepReason: 
      type: string
     Prefix: 
      type: string
     ApplicationDate: 
      type: string
     Language: 
      type: string
     Phone: 
      type: string
     altFormatRqst: 
      type: string
     ZipCode: 
      type: string
     StateCode: 
      type: string
     SeparationReasonDescription: 
      type: string
     GroupId: 
      type: string
     Firstname: 
      type: string
     MedicareNumber: 
      type: string
     ElectionType: 
      type: string
     BrokerAttestationType: 
      type: string
  parameters: 
   TenantIdentifierParam: 
    in: header
    name: TenantIdentifier
    required: false
    schema: 
     type: string
    description: Tenant Identifier
   client_secretParam: 
    in: header
    name: client_secret
    required: true
    schema: 
     type: string
    description: description of parameter passed
   client_idParam: 
    in: header
    name: client_id
    required: true
    schema: 
     type: string
    description: description of parameter passed
   channelidParam: 
    in: header
    name: channelid
    required: false
    schema: 
     type: string
     format: integer | nil
    description: Unique Id to determine the Client
   memberIdQueryParam: 
    in: query
    name: memberIdQuery
    required: true
    schema: 
     type: integer
    description: Unique member Id
