openapi: 3.0.0
info: 
  version: 1.0.0
  title: EIC-Admin-Exp-Api
  description: API description
servers: 
  - url: api
    description: API Server Description
paths: 
  /member: 
   post: 
    operationId: postmember
    tags: 
     - member
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/memberInsertRequest'
    parameters: 
     - $ref: '#/components/parameters/TenantIdentifierParam'
     - $ref: '#/components/parameters/client_secretParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/channelidParam'
    responses: 
     '200': 
      description: Success
      content: 
       application/json: 
                                                    schema:
                                                     type: string
     '500': 
      description: Success
      content: 
       application/json: 
                                                    schema:
                                                     type: string
   get: 
    operationId: getmember
    tags: 
     - member
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/memberIdQueryParam'
     - $ref: '#/components/parameters/client_secretParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/channelidParam'
    responses: 
     '200': 
      description: Success
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/membergetResponse'
     '500': 
      description: Internal Server Error
     '404': 
      description: Not found
   put: 
    operationId: putmember
    tags: 
     - member
    description: Description of path
    requestBody: 
     required: true
     content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/memberUpdateRequest'
    parameters: 
     - $ref: '#/components/parameters/client_secretParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/channelidParam'
    responses: 
     '200': 
      description: Success
      content: 
       application/json: 
                                                    schema:
                                                     type: string
     '500': 
      description: Success
      content: 
       application/json: 
                                                    schema:
                                                     type: string
components: 
  schemas: 
   memberInsertRequest: 
    type: object
    properties: 
     ReferralCode: 
      type: string
     Email: 
      type: string
     Gender: 
      type: string
     MiddleInitial: 
      type: string
     DateOfBirth: 
      type: string
     CmsConfirmationId: 
      type: string
     AltPhone: 
      type: string
     LastName: 
      type: string
     ApplicationId: 
      type: string
     CellPhone: 
      type: string
     SepReason: 
      type: string
     Prefix: 
      type: string
     ApplicationDate: 
      type: string
     Language: 
      type: string
     Phone: 
      type: string
     altFormatRqst: 
      type: string
     ZipCode: 
      type: string
     StateCode: 
      type: string
     SeparationReasonDescription: 
      type: string
     GroupId: 
      type: string
     Firstname: 
      type: string
     MedicareNumber: 
      type: string
     ElectionType: 
      type: string
     BrokerAttestationType: 
      type: string
   ReferralCode: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   Email: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
   Address: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
     required: 
      type: string
   Gender: 
    type: object
    properties: 
     type: 
      type: string
     type: 
      type: string
   Institution: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   MiddleInitial: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
   BrokerAttestation: 
    type: object
    properties: 
     type: 
      type: string
     type: 
      type: string
   DateOfBirth: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   PartAEffDate: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   CmsConfirmationId: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
   AltPhone: 
    type: object
    properties: 
     type: 
      type: string
     type: 
      type: string
   spouseWorkInd: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   LastName: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
   ApplicationId: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   EmergencyContact: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   HasEmergencyContact: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   CellPhone: 
    type: object
    properties: 
     type: 
      type: string
     type: 
      type: string
   HasOtherCoverage: 
    type: object
    properties: 
     type: 
      type: string
   SepReason: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   Prefix: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
   ApplicationDate: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   selfWorkInd: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   EnrollmentDate: 
    type: object
    properties: 
     type: 
      type: string
   OtherCoverage: 
    type: object
    properties: 
     type: 
      type: string
   Language: 
    type: object
    properties: 
     type: 
      type: string
   Phone: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
     type: 
      type: string
   altFormatRqst: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   EnrollmentType: 
    type: object
    properties: 
     format: 
      type: string
     type: 
      type: string
   PaymentType: 
    type: object
    properties: 
     format: 
      type: string
     type: 
      type: string
   IsLongTermCare: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   DeductSsa: 
    type: object
    properties: 
     type: 
      type: string
   Broker: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   LoginId: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   ZipCode: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
   StateCode: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   MailingAddress: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   HasBroker: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   Plan: 
    type: object
    properties: 
     type: 
      type: string
   PartBEffDate: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   SeparationReasonDescription: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   GroupId: 
    type: object
    properties: 
     type: 
      type: string
     type: 
      type: string
   Firstname: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
   MedicareNumber: 
    type: object
    properties: 
     type: 
      type: string
     type: 
      type: string
   UserId: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   ElectionType: 
    type: object
    properties: 
     type: 
      type: string
   IsRepresentative: 
    type: object
    properties: 
     type: 
      type: string
   BrokerAttestationType: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   Representative: 
    type: object
    properties: 
     type: 
      type: string
   properties: 
    type: object
    properties: 
     Email: 
      type: object
      $ref: '#/components/schemas/Email'
     Address: 
      type: object
      $ref: '#/components/schemas/Address'
     Phone: 
      type: object
      $ref: '#/components/schemas/Phone'
     Relationship: 
      type: object
      $ref: '#/components/schemas/Relationship'
     Name: 
      type: object
      $ref: '#/components/schemas/Name'
   Relationship: 
    type: object
    properties: 
     type: 
      type: string
   Name: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   IsBroker: 
    type: object
    properties: 
     type: 
      type: string
     type: 
      type: string
   memberUpdateRequest: 
    type: object
    properties: 
     MZipCode: 
      type: string
     Email: 
      type: string
     GreenEobReasonCode: 
      type: string
     MCity: 
      type: string
     BWritingCode: 
      type: string
     CellPhone: 
      type: string
     AltMemberId: 
      type: string
     Prefix: 
      type: string
     Gender: 
      type: string
     PlanName: 
      type: string
     HICN: 
      type: string
     MailNABPs: 
      type: string
     MiddleInitial: 
      type: string
     MBI: 
      type: string
     Phone: 
      type: string
     PbpCode: 
      type: string
     MAddress2: 
      type: string
     Status: 
      type: string
     MAddress1: 
      type: string
     FirstName: 
      type: string
     ZipCode: 
      type: string
     Address2: 
      type: string
     MState: 
      type: string
     Address1: 
      type: string
     City: 
      type: string
     GroupId: 
      type: string
     MedicareNumber: 
      type: string
     AltPhone: 
      type: string
     CMSConfirmationID: 
      type: string
     State: 
      type: string
     LastName: 
      type: string
   MZipCode: 
    type: object
    properties: 
     type: 
      type: string
   GreenEobReasonCode: 
    type: object
    properties: 
     type: 
      type: string
   MCity: 
    type: object
    properties: 
     type: 
      type: string
   BWritingCode: 
    type: object
    properties: 
     type: 
      type: string
   CurrentBalance: 
    type: object
    properties: 
     format: 
      type: string
     type: 
      type: string
   AltMemberId: 
    type: object
    properties: 
     type: 
      type: string
   PlanName: 
    type: object
    properties: 
     type: 
      type: string
   PbpId: 
    type: object
    properties: 
     format: 
      type: string
     type: 
      type: string
   HICN: 
    type: object
    properties: 
     type: 
      type: string
   MemberId: 
    type: object
    properties: 
     format: 
      type: string
     type: 
      type: string
   MailNABPs: 
    type: object
    properties: 
     type: 
      type: string
   MBI: 
    type: object
    properties: 
     type: 
      type: string
   DOB: 
    type: object
    properties: 
     type: 
      type: string
   PbpCode: 
    type: object
    properties: 
     type: 
      type: string
   DisenrollmentDate: 
    type: object
    properties: 
     type: 
      type: string
   MAddress2: 
    type: object
    properties: 
     type: 
      type: string
   Status: 
    type: object
    properties: 
     type: 
      type: string
     enum: 
      type: string
   MAddress1: 
    type: object
    properties: 
     type: 
      type: string
   PrimaryPharmacy: 
    type: object
    properties: 
     type: 
      type: string
   FirstName: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
   PlanId: 
    type: object
    properties: 
     format: 
      type: string
     type: 
      type: string
   Address2: 
    type: object
    properties: 
     type: 
      type: string
   MState: 
    type: object
    properties: 
     type: 
      type: string
   Address1: 
    type: object
    properties: 
     type: 
      type: string
   City: 
    type: object
    properties: 
     type: 
      type: string
   Pharmacies: 
    type: object
    properties: 
     type: 
      type: string
   items: 
    type: object
    properties: 
     type: 
      type: string
   MonthlyPremium: 
    type: object
    properties: 
     format: 
      type: string
     type: 
      type: string
   PbpEffectiveDate: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
   CMSConfirmationID: 
    type: object
    properties: 
     type: 
      type: string
     required: 
      type: string
     type: 
      type: string
   Year: 
    type: object
    properties: 
     format: 
      type: string
     type: 
      type: string
   State: 
    type: object
    properties: 
     type: 
      type: string
  parameters: 
   TenantIdentifierParam: 
    in: header
    name: TenantIdentifier
    required: false
    schema: 
     type: string
    description: Tenant Identifier
   client_secretParam: 
    in: header
    name: client_secret
    required: true
    schema: 
     type: string
    description: description of parameter passed
   client_idParam: 
    in: header
    name: client_id
    required: true
    schema: 
     type: string
    description: description of parameter passed
   channelidParam: 
    in: header
    name: channelid
    required: false
    schema: 
     type: string
     format: integer | nil
    description: Unique Id to determine the Client
   memberIdQueryParam: 
    in: query
    name: memberIdQuery
    required: true
    schema: 
     type: integer
    description: Unique member Id
