openapi: 3.0.0
info: 
  version: 1.0.0
  title: Contract Rates API
  description: API for getting Contract Rates
servers: 
  - url: https://hexapi.example.com
    description: API Server Description
security: 
  - BasicAuth: []
paths: 
components: 
  securitySchemes: 
   BasicAuth: 
    type: http
    scheme: basic
