openapi: 3.0.0
info: 
  version: 1.0.0
  title: EIC-Admin-Exp-Api
  description: API description
servers: 
  - url: api
    description: API Server Description
paths: 
  /SSADeductExport/{UserName}: 
   get: 
    operationId: getDeductExport_UserNameget
    tags: 
     - SSADeductExport
    description: Description of path
    parameters: 
     - $ref: '#/components/parameters/TenantIdentifierParam'
     - $ref: '#/components/parameters/client_secretParam'
     - $ref: '#/components/parameters/client_idParam'
     - $ref: '#/components/parameters/channelidParam'
    responses: 
     '200': 
      description: Success
      content: 
       application/json: 
        schema: 
         $ref: '#/components/schemas/SSADeductExportgetResponse'
     '500': 
      description: Success
      content: 
       application/json: 
