openapi: 3.0.0
info: 
  version: 1.0.0
  title: EIC-Admin-Exp-Api
  description: API description
servers: 
  - url: api
    description: API Server Description
paths: 
components: 
  parameters: 
   UserNameParam: 
    in: path
    name: UserName
    required: true
    schema: 
     type: string
    description: Unique UserName
